import type { ProjectThemeDefinition } from './theme-system';

const sans = 'Inter, ui-sans-serif, system-ui, sans-serif';
const mono = 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace';

export const BUILTIN_PROJECT_THEMES: readonly ProjectThemeDefinition[] = [
  {
    id: 'frontend.minimal-clean',
    version: 1,
    scope: 'frontend',
    label: 'Minimal Clean',
    description: 'Neutral, spacious and typography-first frontend foundation.',
    tokens: {
      color: { background: '#ffffff', surface: '#f8fafc', text: '#111827', muted: '#64748b', accent: '#2563eb' },
      typography: { fontFamily: sans, headingWeight: 700, bodyWeight: 400 },
      shape: { radius: 8 },
      spacing: { density: 'comfortable', base: 8 },
    },
  },
  {
    id: 'frontend.bento-grid',
    version: 1,
    scope: 'frontend',
    label: 'Bento Grid',
    description: 'Modular card-oriented frontend with strong grouped hierarchy.',
    tokens: {
      color: { background: '#f4f7fb', surface: '#ffffff', text: '#111827', muted: '#64748b', accent: '#4f46e5' },
      typography: { fontFamily: sans, headingWeight: 750, bodyWeight: 400 },
      shape: { radius: 18 },
      spacing: { density: 'comfortable', base: 10 },
    },
  },
  {
    id: 'frontend.elegant-editorial',
    version: 1,
    scope: 'frontend',
    label: 'Elegant Editorial',
    description: 'Editorial composition with stronger type hierarchy and restrained surfaces.',
    tokens: {
      color: { background: '#fbfaf7', surface: '#ffffff', text: '#1f1d1a', muted: '#746f68', accent: '#8a5a44' },
      typography: { fontFamily: 'Georgia, Cambria, Times New Roman, serif', headingWeight: 700, bodyWeight: 400 },
      shape: { radius: 4 },
      spacing: { density: 'spacious', base: 12 },
    },
  },
  {
    id: 'frontend.sophisticated-dark',
    version: 1,
    scope: 'frontend',
    label: 'Sophisticated Dark',
    description: 'Premium dark frontend with restrained contrast and crisp accents.',
    tokens: {
      color: { background: '#0c0f14', surface: '#151922', text: '#f4f6fb', muted: '#9aa4b5', accent: '#7c9cff' },
      typography: { fontFamily: sans, headingWeight: 700, bodyWeight: 400 },
      shape: { radius: 10 },
      spacing: { density: 'comfortable', base: 8 },
    },
  },
  {
    id: 'frontend.material-neutral',
    version: 1,
    scope: 'frontend',
    label: 'Material Neutral',
    description: 'Neutral Material-inspired frontend with expressive but accessible surfaces.',
    tokens: {
      color: { background: '#f9f9ff', surface: '#ffffff', text: '#1b1b1f', muted: '#5f6368', accent: '#6750a4' },
      typography: { fontFamily: sans, headingWeight: 650, bodyWeight: 400 },
      shape: { radius: 16 },
      spacing: { density: 'comfortable', base: 8 },
    },
  },
  {
    id: 'frontend.neobrutalist-modern',
    version: 1,
    scope: 'frontend',
    label: 'Neobrutalist Modern',
    description: 'High-contrast graphic frontend with hard borders and bold hierarchy.',
    tokens: {
      color: { background: '#fffdf5', surface: '#ffffff', text: '#111111', muted: '#4b5563', accent: '#ff5c35' },
      typography: { fontFamily: sans, headingWeight: 850, bodyWeight: 500 },
      shape: { radius: 2, borderWidth: 2 },
      spacing: { density: 'compact', base: 8 },
    },
  },
  {
    id: 'frontend.corporate-pro',
    version: 1,
    scope: 'frontend',
    label: 'Corporate Pro',
    description: 'Trust-oriented corporate frontend for professional and enterprise sites.',
    tokens: {
      color: { background: '#f7f9fc', surface: '#ffffff', text: '#172033', muted: '#62708a', accent: '#174ea6' },
      typography: { fontFamily: sans, headingWeight: 700, bodyWeight: 400 },
      shape: { radius: 6 },
      spacing: { density: 'comfortable', base: 8 },
    },
  },
  {
    id: 'frontend.glassmorphism',
    version: 1,
    scope: 'frontend',
    label: 'SaaS Glassmorphism',
    description: 'Layered SaaS frontend with translucent surfaces and accessible foreground contrast.',
    tokens: {
      color: { background: '#10152a', surface: '#1b2342cc', text: '#f8faff', muted: '#b6c2df', accent: '#65a8ff' },
      typography: { fontFamily: sans, headingWeight: 700, bodyWeight: 400 },
      shape: { radius: 16, blur: 16 },
      spacing: { density: 'comfortable', base: 8 },
    },
  },
  {
    id: 'backend.high-density',
    version: 1,
    scope: 'backend',
    label: 'High Density',
    description: 'Maximum information visibility for administration and operational work.',
    tokens: {
      color: { background: '#f1f4f8', surface: '#ffffff', text: '#172033', muted: '#657287', accent: '#2563eb' },
      typography: { fontFamily: sans, headingWeight: 700, bodyWeight: 400 },
      shape: { radius: 5 },
      spacing: { density: 'dense', base: 6, rowHeight: 34 },
    },
  },
  {
    id: 'backend.saas-dashboard',
    version: 1,
    scope: 'backend',
    label: 'SaaS Dashboard',
    description: 'Crisp SaaS administration with compact cards and strong status hierarchy.',
    tokens: {
      color: { background: '#f6f8fc', surface: '#ffffff', text: '#172033', muted: '#64748b', accent: '#4f46e5' },
      typography: { fontFamily: sans, headingWeight: 700, bodyWeight: 400 },
      shape: { radius: 8 },
      spacing: { density: 'dense', base: 8, rowHeight: 36 },
    },
  },
  {
    id: 'backend.enterprise-corporate',
    version: 1,
    scope: 'backend',
    label: 'Enterprise / Corporate',
    description: 'Conservative administration system optimized for long working sessions.',
    tokens: {
      color: { background: '#eef2f6', surface: '#ffffff', text: '#1d2939', muted: '#667085', accent: '#175cd3' },
      typography: { fontFamily: sans, headingWeight: 650, bodyWeight: 400 },
      shape: { radius: 4 },
      spacing: { density: 'dense', base: 6, rowHeight: 34 },
    },
  },
  {
    id: 'backend.developer-console',
    version: 1,
    scope: 'backend',
    label: 'Developer Console',
    description: 'Technical dark administration theme with monospace data emphasis.',
    tokens: {
      color: { background: '#0b0f14', surface: '#111820', text: '#dce7f4', muted: '#7f91a7', accent: '#46b4ff' },
      typography: { fontFamily: mono, headingWeight: 650, bodyWeight: 400 },
      shape: { radius: 3 },
      spacing: { density: 'dense', base: 6, rowHeight: 32 },
    },
  },
  {
    id: 'backend.monochrome-pro',
    version: 1,
    scope: 'backend',
    label: 'Monochrome Pro',
    description: 'Grayscale administration chrome with one functional accent.',
    tokens: {
      color: { background: '#f4f4f5', surface: '#ffffff', text: '#18181b', muted: '#71717a', accent: '#27272a' },
      typography: { fontFamily: sans, headingWeight: 700, bodyWeight: 400 },
      shape: { radius: 4 },
      spacing: { density: 'dense', base: 6, rowHeight: 34 },
    },
  },
  {
    id: 'backend.material-neutral',
    version: 1,
    scope: 'backend',
    label: 'Material Neutral',
    description: 'Material-inspired admin surfaces with compact expressive controls.',
    tokens: {
      color: { background: '#f6f5fa', surface: '#ffffff', text: '#1d1b20', muted: '#69656f', accent: '#6750a4' },
      typography: { fontFamily: sans, headingWeight: 650, bodyWeight: 400 },
      shape: { radius: 12 },
      spacing: { density: 'compact', base: 8, rowHeight: 38 },
    },
  },
  {
    id: 'backend.sophisticated-dark',
    version: 1,
    scope: 'backend',
    label: 'Sophisticated Dark',
    description: 'Dark professional admin surface with restrained elevation and contrast.',
    tokens: {
      color: { background: '#0f1117', surface: '#181b23', text: '#f2f4f8', muted: '#9ca4b3', accent: '#8aa4ff' },
      typography: { fontFamily: sans, headingWeight: 700, bodyWeight: 400 },
      shape: { radius: 8 },
      spacing: { density: 'dense', base: 7, rowHeight: 36 },
    },
  },
];
